naam= input('wat is je naam?')
address = input('wat is je address?')
postcode = input('wat is je postcode?')
woonplaats = input('wat is je woonplaats?')
print( "-" * 50)
print(f"|  Naam      : {naam} ")
print(f"|  Adres     : {address} ")
print(f"|  Postcode  : {postcode} ")
print(f"|  Woonplaats: {woonplaats} ")
print("-" * 50)