naam = input('Hallo, wat is je naam?')
leeftijd = input (f'goedendag {naam}, hoe oud ben je? ')
eten = input(f'en als {leeftijd}, wat eet je het liefst?')
drinken = input(f' en wat drink je het liefst bij je {eten}?')
input(f'de {leeftijd} {naam} drinkt het liefst {drinken} bij {eten}.')